Feat/9 create education entity api
ssafy-a-stroke-of-genius/simulated-stock-investment pull request #11
Opened 2023-11-08 23:26 UTC by KimDahui42

2023-11-08 23:37 UTC, RIN-1011 requested changes

2023-11-08 23:37 UTC, RIN-1011 commented on mock-stock-investment/src/main/java/com/ssafy/mockstockinvestment/education/EducationCategoryEnum.java
> +    금융,경제,부동산
영어로 변경 및 카테고리 재구성

2023-11-09 00:58 UTC, heeseungy approved these changes

2023-11-09 12:26 UTC, RIN-1011 approved these changes

2023-11-09 12:26 UTC, merged